title: BAPL Support
description: APL Support
theme: just-the-docs


url: https://patjas211.github.io/t234/
enable_copy_code_button: true
logo: "/assets/images/logo4.png"
aux_links:
  "Infosys":
    - "https://infosys.beckhoff.com/index_en.htm"
aux_links_new_tab: true
url: https://infosys.beckhoff.com/index_en.htm

aux_links:
  Infosys: https://infosys.beckhoff.com/index_en.htm

permalink: pretty

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.6"
